### PR TITLE
Fix installer issues

### LINKED ISSUE #91: Fix installer
- Don't pass password as flag in installer
- Refactor installer to more manageable structure.

### PR DESCRIPTION
**Pull request by tamalsaha**
Fixes #91

### CODE REVIEW

File: installer/deployment.go [hunk 1]
```diff
@@ -0,0 +1,172 @@
...
+	d.Spec.Template.Spec.Containers[0].Args = append(d.Spec.Template.Spec.Containers[0].Args, server.SecureServingOptions{}.ToArgs()...)
+	d.Spec.Template.Spec.Containers[0].Args = append(d.Spec.Template.Spec.Containers[0].Args, opts.Token.ToArgs()...)
+	d.Spec.Template.Spec.Containers[0].Args = append(d.Spec.Template.Spec.Containers[0].Args, opts.Google.ToArgs()...)
+	d.Spec.Template.Spec.Containers[0].Args = append(d.Spec.Template.Spec.Containers[0].Args, opts.Azure.ToArgs()...)
+	d.Spec.Template.Spec.Containers[0].Args = append(d.Spec.Template.Spec.Containers[0].Args, opts.LDAP.ToArgs()...)
+
+	return &d
+}
+
+func newSecretForTokenAuth(namespace string, data map[string][]byte) runtime.Object {
```
Comment (nightfury1204) [inline installer/deployment.go]: shouldn't it be in installer/secret.go

File: installer/deployment.go [hunk 2]
```diff
@@ -0,0 +1,172 @@
...
+		ObjectMeta: metav1.ObjectMeta{
+			Name:      "guard-auth",
+			Namespace: namespace,
+			Labels:    labels,
+		},
+		Data: data,
+	}
+}
+
+func newSecretForLDAP(namespace string, data map[string][]byte) runtime.Object {
```
Comment (nightfury1204) [inline installer/deployment.go]: shouldn't it be in installer/secret.go

File: commands/installer.go [hunk 3]
```diff
@@ -1,465 +1,24 @@
...
-	addr            string
-	runOnMaster     bool
-	privateRegistry string
-	imagePullSecret string
-
-	Token  token.Options
-	Google google.Options
-	Azure  azure.Options
-	LDAP   ldap.Options
+var labels = map[string]string{
```
Comment (nightfury1204) [inline commands/installer.go]: unused variable
